<?php
// Operator autoloading
$eZTemplateOperatorArray = array();
$eZTemplateOperatorArray[] = array( 'script' => 'extension/ezServerUtil/autoloads/ezServerUtil.php',
                                    'class' => 'ezServerUtil',
                                    'operator_names' => array(
																'sessionset',
																'sessionget',
																'removefromsession',
																'redirectabsolute',
																'redirectrelative',
																'sessionSet',
																'sessionGet',
																'removeFromSession',
																'getPost',
																'getSession',
																'isMail',
																'getGet',
																'getServer',
																'aSort',
																'arSort',
																'krSort',
																'kSort',
																'KShuffle',
																'Shuffle',
																'strStr',
																'stripTags',
																'arrayCountValues',
																'flashReplace',
																'flashReplaceT',
																'youTube',
																'arrayKey',
																'strReplace',
																'addToArray',
																'dateTime',
																'checkDate',																
																'strrChr',
																'strToTime',
																'Round',
																'getsiteaccess',
																'getGlobals',
																'getglobals',
																'globalsset',
																'globalsget',
																'globalget',
																'globalset',
																'removefromglobals',
																'removeFromGlobals',
															)
								);
?>
